services:
  backend:
    build:
      context: backend
    ports:
      - '8080:8080'
  frontend:
    build:
      context: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm run dev