version: '3.9'

services:

  engine:
    build:
      context: ../engine
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_NAME: ${APP_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      STORAGE_DIRECTORY: ${STORAGE_DIRECTORY}
      NODE_SERVICE_URL: ${NODE_SERVICE_URL}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      FLYWAY_ENABLED: true
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}
    volumes:
      - ../engine/build/libs:/app/libs
    command: java -jar /app/libs/engine-0.0.1-SNAPSHOT.jar
  
  node:
    build:
      context: ../node
    ports:
      - "8000:8000"
    volumes:
      - ../node:/app
    environment:
      ENGINE_SERVICE_URL: ${ENGINE_SERVICE_URL}
  
  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend/src:/app/src
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm run dev

volumes:
  postgres_data:
  grafana_data: