spring:
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver

    flyway:
      enabled: true
      baseline-on-migrate: true
      baseline-version: 0
      locations: classpath:db/migration

storage.directory: ${STORAGE_DIRECTORY}
node.service.url: ${NODE_SERVICE_URL}

logging:
  level:
    org.springframework.web: INFO
    org.springframework.boot.actuate: INFO
management:
  metrics:
    enable:
      jvm: true
    tags:
      application: graph-processor
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health", "info"]