spring:
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB

storage:
  images: upload-image-dir
  temp-images: temp-image-dir

logging:
  level:
    org.springframework.web: DEBUG