[tool.poetry]
name = "pixel"
version = "0.1.0"

[tool.poetry.dependencies]
python = {}
torch = {}
torchvision = {}
numpy = {}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"